lib/questionnaires/model/src/questionnaire_item_model.dart
This PR allows items nested within `type: 'group'` items to be hidden if the parent group itself is already hidden.
Thus, it's only necessary for a group to be declared like:
```
{
"extension": [
{
"url": "http://hl7.org/fhir/StructureDefinition/questionnaire-hidden",
"valueBoolean": true
}
],
"type": "group",
"text": "Hidden Group",
"item": [
{
"type": "string",
"text": "Hidden question"
},
...
]
}
```
in order to make itself and all of its children hidden.
=> Hide nested items of hidden items

example/lib/main.dart
Apparently this was just a matter of setting `useMaterial3` properly.
=> Fix time picker time display in example app

lib/questionnaires/model/item/src/response_node.dart, lib/questionnaires/model/src/questionnaire_response_model.dart, lib/questionnaires/view/src/questionnaire_filler.dart, lib/questionnaires/view/src/questionnaire_stepper.dart, lib/questionnaires/view/src/questionnaire_theme.dart
* Fixes a bug in which `QuestionnaireStepper` shows blank screens for hidden/disabled items.
* Adds a `QuestionnaireTheme.stepperGroupDisplayPreference` setting, which allows showing groups and nested items as a single step, instead of each item in separate steps/pages.
* Adds a `QuestionnaireTheme.showScore` setting, which allows hiding score at the bottom of QuestionnaireStepper views.
* Adds a `onQuestionnaireResponseChanged` callback to `QuestionnaireStepper`, similar to the one in `QuestionnaireScroller`.
For example, to use the new settings in the example app with the `PHQ9 Questionnaire Stepper` questionnaire: 
```dart
...
ListTile(
title: const Text('PHQ9 Questionnaire Stepper'),
subtitle: const Text(
'Simple choice-based survey with a total score.',
),
onTap: () {
Navigator.push( …
```
=> QuestionnaireStepper improvements

lib/questionnaires/view/item/answer/src/attachment_answer_filler.dart, lib/questionnaires/view/item/answer/src/boolean_answer_filler.dart, lib/questionnaires/view/item/answer/src/coding_answer_filler.dart, lib/questionnaires/view/item/answer/src/datetime_answer_filler.dart, lib/questionnaires/view/item/answer/src/numerical_answer_filler.dart, lib/questionnaires/view/item/answer/src/string_answer_filler.dart, lib/questionnaires/view/item/src/display_item.dart, lib/questionnaires/view/item/src/group_item.dart, lib/questionnaires/view/item/src/question_response_item_filler.dart, lib/questionnaires/view/item/src/questionnaire_item_filler_title.dart, lib/questionnaires/view/src/questionnaire_scroller.dart, lib/questionnaires/view/src/questionnaire_stepper.dart, lib/questionnaires/view/src/questionnaire_theme.dart
This PR introduces multiples changes to allow customizing layouts in the app.
The idea is to have a set of default layout builder functions that can be overridden in `QuestionnaireTheme`.
These changes try to keep paddings and other UI-related requirements within these functions as much as possible, so that these can be easily overridden afterwards.
=> Preliminary Theming/Layout Support

example/lib/custom_questionnaire_stepper_page.dart, example/lib/main.dart, lib/questionnaires/view/src/questionnaire_stepper.dart
This PR accepts the following parameters when building a QuestionnareStepper
- `void onPageChanged(int)`: This will be used for the parent to know when the page is changed
- `PageController`: This will be used so the parent controller can control the page view, e.g. next or previous page.
I added `CustomQuestionnaireStepperPage`  as a PoC.
=> Expose PageController of QuestionnaireStepper

lib/fhir_types/src/date_time_picker.dart, lib/questionnaires/model/item/answer/src/datetime_answer_model.dart, lib/questionnaires/view/item/answer/src/datetime_answer_filler.dart
This PR introduces the following changes:
* Refactors date/time formatting in `date_time_picker.dart` into a single implementation.
* Fixes time filler answers not being repopulated after rerendering or loading previously saved responses. 
Details about how to reproduce the issue are in https://github.com/sujrd/faiadashu/issues/27
=> Fix time filler data population on re-rendering

lib/fhir_types/src/date_time_picker.dart, lib/questionnaires/view/item/answer/src/datetime_answer_filler.dart, lib/questionnaires/view/src/questionnaire_theme.dart
Allows setting `showDatePicker` and `showTimePicker`'s `initialEntryMode` property from `QuestionnaireTheme`.
=> Allow customizing time/date picker entry modes via QuestionnaireTheme

lib/questionnaires/model/item/answer/src/numerical_answer_model.dart, lib/questionnaires/view/item/answer/src/numerical_answer_filler.dart
This PR addresses the following:
* Adds support for the `unitOption` extension to show the unit selector in quantity items that have it.
* Fixes vertical position of field units when there's only a single unitOption (no dropdown).
* Fixes a bug in which units would not be set in the response for quantity items/questions with a single unit option.
* Behavior changes:
* First unit is now selected by default when there's no answer to a quantity question item.
* Empty units cannot be selected.
=> Support unitOption extension

example/lib/custom_questionnaire_stepper_page.dart, lib/questionnaires/view/src/questionnaire_stepper.dart, lib/questionnaires/view/src/questionnaire_stepper_page_view.dart, lib/questionnaires/view/src/questionnaire_theme.dart
Basically, this PR introduces `onLastPageUpdated` in QuestionnaireStepper, so parent widget can know when the last page is really reached.
We check the state when the page index is changed and the questionnaire response is updated.
______
In our internal app, we need a way to know exactly which QuestionnaireItemFiller is currently shown. `onVisibleItemUpdated`  callback is added in `QuestionnaireStepper`. This will be called for the following scenarios:
- page index is changed.
- page view item is updated.
=> Introduce onLastPageUpdated in QuestionnaireStepper

lib/questionnaires/model/item/answer/src/numerical_answer_model.dart, lib/questionnaires/model/src/questionnaire_model_defaults.dart
Example of how it shows:
I could either use code or display, I think code is more appropiate for this implementation.
=> Support questionnaire-unit extension

lib/questionnaires/model/item/answer/src/numerical_answer_model.dart, lib/questionnaires/model/src/questionnaire_model_defaults.dart
Shows unit `display` in `questionnaire-unit` extension if present.
=> Change behavior of questionnaire-unit to work as defined in R5

lib/fhir_types/src/date_time_picker.dart, lib/fhir_types/src/fhir_types_extensions.dart
The problem is that, in any of these scenarios:
* Setting an initial value for a datetime field with timezone other than local.
* Loading a QuestionnaireResponse with a datetime response in timezone other than local.
The value itself will be auto converted to UTC, and displayed in such a way, which may be confusing.
The current PR converts datetimes to local before displaying them and shows the TZ info as well.
Unfortunately, Dart cannot handle timezones other than UTC or local (https://stackoverflow.com/a/52325454), so we cannot show the datetime in the original timezone.
=> Fix population of datetimes with TZ info

example/assets/instruments/sdc_demo.json, lib/questionnaires/model/item/answer/src/numerical_answer_model.dart, lib/questionnaires/view/item/answer/src/numerical_input_formatter.dart
This PR contains the following changes:
* Fixes numerical inputs not respecting the number of decimal digits specified in the `maxDecimalPlaces` extension.
* Simplifies how the number formatter is built by using `NumberFormat.decimalPatternDigits`.
* Removes some logic for constraining the amount of digits in the integer part of numbers:
* If needed, we can implemented.
* From what I could see, this also didn't work as expected, in the same way as constraining decimal digits didn't work, so you could type long integer numbers anyway.
* The restriction was based only on `maxValue`, so it may or may not have caused issues with negative numbers.
* If `maxDecimalPlaces` is not specified, by default the max number of decimals digits is set to 3.
* Apparently this was the original intended …
=> Fix maxDecimalPlaces behavior

lib/questionnaires/view/item/answer/src/numerical_answer_filler.dart
Fixes #56.
The error is introduced because of using the non-nullable operator (!) when the value of `answerModel.value.value` can be actually null.
=> Fix numeric field null check errors

lib/questionnaires/view/item/answer/src/coding_answer_filler.dart
fixes #65 
Allows changing the background of choice options from the app's main theme.
To test, in the example app, you can try adding a `cardTheme` to the app's theme:
```
theme: ThemeData.light(useMaterial3: true).copyWith(
colorScheme: ColorScheme.fromSeed(seedColor: Colors.pink),
inputDecorationTheme:
ThemeData.light(useMaterial3: true).inputDecorationTheme.copyWith(
filled: true,
),
// Card theme here
cardTheme: ThemeData.light(useMaterial3: true).cardTheme.copyWith(
elevation: 4,
color: Colors.blue,
),
...
),
```
=> Allow overriding choice option background properties

lib/questionnaires/model/item/src/question_item_model.dart
fixes #45 
Adds support to set initial values for choice and open-choice questions via [answerOption.initialSelected](http://hl7.org/fhir/R5/questionnaire-definitions.html#Questionnaire.item.answerOption.initialSelected).
This could be verified easily with the SDC Demo form example.
This one already has a `Gender` question in which `initialSelected` is set to true for the `Female` option, but thus far was being ignored.
The form also has multiple open-choice questions which can be used to test this.
=> Add support for initialSelected in choice and open-choice questions

example/lib/custom_questionnaire_stepper_page.dart, lib/questionnaires/view/src/questionnaire_stepper.dart, lib/questionnaires/view/src/questionnaire_stepper_page_view.dart
This PR makes the following changes:
* Adds a `QuestionnaireStepperPageViewData` inherited widget
* Provides access to the stepper `controller`
* Adds a `QuestionnaireStepperPageView.of` method to get back a `QuestionnaireStepperPageViewData` if invoked form within the rendering tree.
* Adds methods to transition to a specific stepper page.
* Fixes a bug in which the stepper `next` button would not go to the next page, unless a controller was provided.
=> Provide inherited access to stepper controller

example/pubspec.lock, example/pubspec.yaml, faiabench/pubspec.yaml, faiadashu_online/pubspec.yaml, lib/questionnaires/view/src/webview_html.dart, lib/questionnaires/view/src/webview_io.dart, pubspec.yaml
This PR updates the following packages:
* `file_selector`: Used for attachment questions
* `markdown`: For supporting the rendering-markdown extension
* The Hot Beverage IG questionnaire has an example of this.
* `simple_html_css`: For rendering the rendering-xhtml extension
* This is actually always used to render the text of all questions
* `webview_flutter` and `webview_flutter_web`: 
* Used for rendering the Narrative panels toggled via the top-right button on the example app.
* Updates the implementation to use the new API usage specified in the docs.
Additionally, this also raises the minimum versions of the Flutter and Dart SDKs.
=> Update minor packages

lib/questionnaires/view/src/questionnaire_filler.dart
Fixes #75 
Creates QuestionnaireResponseModel only once across rebuilds of QuestionnaireFiller.
Apparently this was added recently in #49.
@hanny-ph I found the issue earlier while working on the package upgrades by chance.
Could you check on your side if with these changes we can still achieve what we were trying to do in #49?
=> Fix form flickering on response changes

doc/sdc-capabilities.md, example/assets/instruments/sdc_demo.json, lib/l10n/src/fdash_localizations_ar.dart, lib/l10n/src/fdash_localizations_de.dart, lib/l10n/src/fdash_localizations_en.dart, lib/l10n/src/fdash_localizations_es.dart, lib/l10n/src/fdash_localizations_ja.dart, lib/questionnaires/model/item/answer/src/datetime_answer_model.dart, lib/questionnaires/view/item/answer/src/datetime_answer_filler.dart
Closes #107 
- Adds support for minValue and maxValue extensions in date, time and dateTime items.
- Adds support for dynamic calculation of min/max time ranges via cqf-expression extensions.
- Updates SDC demo Questionnaire with examples of static and dynamic range validations.
- Updates SDC capabilities document.
- Adjusts min/maxValue validation messages to support both numbers and dates/times/datetimes.
- According to the [SDC docs](https://build.fhir.org/ig/HL7/sdc/behavior.html#minValue), dynamic values for min/maxValue extensions can be done with the [cqf-calculatedValue](https://build.fhir.org/ig/HL7/sdc/behavior.html#cqf-calculatedValue) extension.
- Here we implement them with [cqf-expression](https://build.fhir.org/ig/HL7/sdc/behavior.html#cqf-expression) instead.
- While …
=> Add date range validations

example/lib/custom_questionnaire_stepper_page.dart, lib/questionnaires/view/src/questionnaire_stepper_page_view.dart
This PR fixes the bug about onBeforePageChanged not called when jumping to the previous question.
=> Fix onBeforePageChanged not called when jumping to the previous question

lib/questionnaires/view/item/answer/src/boolean_answer_filler.dart
Related to issue(s) #123 
- The issue was that after accepting a Tri-state boolean, it was handled as if `null` was `false` and everything else was `true`. That caused the bug that the initial value as `false` would be turned into a `true` value.
None
=> Resolve: "Questionnaire Item type boolean initial value is always marked as true"

lib/questionnaires/model/aggregation/src/total_score_aggregator.dart, lib/questionnaires/model/item/src/question_item_model.dart
Fixes #138 
- Apparently the `TotalScoreAggregator` runs concurrently during `QuestionnaireResponse` population.
- While the aggregator intends to simply read data to perform calculations, it does so by invoking the `firstAnswerModel` getter in `QuestionItemModel`, which causes it to add a new answer model to the item if one is not present already.
- There appears to be some sort of race condition which makes both answer population and score aggregation call `firstAnswerModel` and cause it to add more than a single answer model.
- The current fix basically avoids calling `firstAnswerModel` from `TotalScoreAggregator` if no answer models are defined yet.
=> Fix QuestionnaireResponse population with scoring
